install:
	../external/ctn/apps/scripts/createdirectory $(MESA_TARGET)/runtime
	cp msgRules.dss $(MESA_TARGET)/runtime
	cp segDefs.dss $(MESA_TARGET)/runtime
	cp msgRules.ihe $(MESA_TARGET)/runtime
	cp segDefs.ihe $(MESA_TARGET)/runtime
	cp msgRules.ihe-iti $(MESA_TARGET)/runtime
	cp segDefs.ihe-iti $(MESA_TARGET)/runtime
	cp msgRules.ordplc $(MESA_TARGET)/runtime
	cp segDefs.ordplc $(MESA_TARGET)/runtime
	cp syslogd* $(MESA_TARGET)/runtime
	cp version.txt $(MESA_TARGET)/runtime
	cp IHE-syslog-audit-message-4.xsd $(MESA_TARGET)/runtime
	cp IHE-ATNA-syslog-audit-message.xsd $(MESA_TARGET)/runtime
	cp xmldsig-core-schema.xsd $(MESA_TARGET)/runtime
	cp MESA-ATNA.xsl $(MESA_TARGET)/runtime
	cp -rp expmgr $(MESA_TARGET)/runtime
	cp -rp exprcr $(MESA_TARGET)/runtime
	cp -rp imgmgr $(MESA_TARGET)/runtime
	cp -rp imgmgr_study $(MESA_TARGET)/runtime
	cp -rp rpt_manager $(MESA_TARGET)/runtime
	cp -rp rpt_repos $(MESA_TARGET)/runtime
	cp -rp wkstation $(MESA_TARGET)/runtime
	cp -rp codes $(MESA_TARGET)/runtime
	cp -rp certificates $(MESA_TARGET)/runtime
	cp -rp ldap $(MESA_TARGET)/runtime
#	cp -rp connectathon $(MESA_TARGET)/runtime
